name: Beri izin eksekusi Gradle Wrapper
run: chmod +x gradlew


name: Pengujian Otomatisasi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pengujian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Beri izin eksekusi Gradle Wrapper
        run: chmod +x gradlew
      
      - name: Atur Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Instal dependensi
        run: ./gradlew dependencies
      
      - name: Jalankan pengujian
        run: ./gradlew test
